import { ReminderInt } from './reminderInt';

let Reminders: ReminderInt[] = [
  {
    id: 1,
    firstname: 'Jane',
    surname: 'Bloggs',
    dob: '07/12/1984',
    email: 'j.bloggs@gmail.com',
    greeting: 'Happy Birthday!',
    gender: 'Female',
  },
  {
    id: 2,
    firstname: 'Jo',
    surname: 'Bloggs',
    dob: '07/12/1984',
    email: 'jo.bloggs@gmail.com',
    greeting: 'Happy Birthday!',
    gender: 'Male',
  },
  {
    id: 3,
    firstname: 'John',
    surname: 'Smith',
    dob: '01/01/1953',
    email: 'jo.smith@gmail.com',
    greeting: 'Happy Birthday!',
    gender: 'Male',
  },
  {
    id: 4,
    firstname: 'Jane',
    surname: 'Bloggs',
    dob: '01/01/1984',
    email: 'j.bloggs@gmail.com',
    greeting: 'Happy Birthday!',
    gender: 'Female',
  },
  {
    id: 5,
    firstname: 'Matt',
    surname: 'Bloggs',
    dob: '01/01/1984',
    email: 'jo.bloggs@gmail.com',
    greeting: 'Happy Birthday!',
    gender: 'Male',
  },
  {
    id: 6,
    firstname: 'Kieran',
    surname: 'Smith',
    dob: '01/01/1953',
    email: 'jo.smith@gmail.com',
    greeting: 'Happy Birthday!',
    gender: 'Male',
  },
  {
    id: 7,
    firstname: 'Leigh',
    surname: 'Bloggs',
    dob: '01/01/1984',
    email: 'j.bloggs@gmail.com',
    greeting: 'Happy Birthday!',
    gender: 'Female',
  },
  {
    id: 8,
    firstname: 'Kelly',
    surname: 'Bloggs',
    dob: '01/01/1984',
    email: 'jo.bloggs@gmail.com',
    greeting: 'Happy Birthday!',
    gender: 'Male',
  },
  {
    id: 9,
    firstname: 'Tina',
    surname: 'Smith',
    dob: '01/01/1953',
    email: 'jo.smith@gmail.com',
    greeting: 'Happy Birthday!',
    gender: 'Male',
  },
  {
    id: 10,
    firstname: 'Adrian',
    surname: 'Asagba',
    dob: '07/13/1984',
    email: 'aasagba@gmail.com',
    greeting: 'Happy Birthday!',
    gender: 'Male',
  },
];

export default Reminders;
